openapi: 3.0.0
info:
  title: Divisions API
  description: This API will give access to divisions data
  version: '2023-12-01'
  contact:
    url: 'https://campminder.com'
paths:
  /:
    get:
      summary: List Divisions
      description: Returns a list of divisions that match the supplied criteria.
      operationId: ListDivisions
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  TotalCount:
                    type: integer
                    description: The total number of records returned in the call.
                  Next:
                    type: string
                    description: The link to the next page of records.
                  Results:
                    type: array
                    description: The array of records returned.
                    items:
                      $ref: '#/components/schemas/DivisionResponse'
        '400':
          description: >-
            This request is invalid. It is either missing required parameters or
            one of the supplied parameters is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 400
                message: '''pagenumber'' is invalid'
        '401':
          description: >-
            This request lacks valid credentials, please try again making sure
            to supply a valid token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 401
                message: Unauthorized
        '403':
          description: >-
            The supplied credentials do not have permission to make this
            request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 403
                message: Forbidden
        '500':
          description: >-
            Our server could not process this request. If the issue persists,
            contact CampMinder support.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 500
                message: Internal Server Error
      parameters:
        - name: Authorization
          in: header
          description: 'The JWT token should be in the format `Bearer {token}`.'
          required: true
          schema:
            type: string
            example: >-
              Bearer
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - name: X-Request-ID
          in: header
          required: false
          description: >-
            If supplied, we can use this to identify exact requests during
            troubleshooting. Must be globally unique to be useful.
          schema:
            type: string
            example: DEEE3D21-F0FA-459E-87BB-A565DBCC0784
        - name: clientid
          in: query
          required: true
          description: The ID of the client to which to limit the results.
          schema:
            type: integer
            format: integer
            example: 444
        - name: pagenumber
          in: query
          required: true
          description: Which page of PageSize results
          schema:
            type: integer
            minimum: 1
            maximum: 1000000000
            format: integer
            example: 10
        - name: pagesize
          in: query
          required: true
          description: How many results per page
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            format: integer
            example: 20
      tags:
        - Divisions
  '/{id}/attendees':
    get:
      summary: List Attendees by Division
      description: Returns division attendees that match the supplied criteria.
      operationId: ListAttendeeIds
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DivisionAttendeeResponse'
        '400':
          description: >-
            This request is invalid. It is either missing required parameters or
            one of the supplied parameters is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 400
                message: '''pagenumber'' is invalid'
        '401':
          description: >-
            This request lacks valid credentials, please try again making sure
            to supply a valid token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 401
                message: Unauthorized
        '403':
          description: >-
            The supplied credentials do not have permission to make this
            request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 403
                message: Forbidden
        '500':
          description: >-
            Our server could not process this request. If the issue persists,
            contact CampMinder support.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 500
                message: Internal Server Error
      parameters:
        - name: Authorization
          in: header
          description: 'The JWT token should be in the format `Bearer {token}`.'
          required: true
          schema:
            type: string
            example: >-
              Bearer
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - name: X-Request-ID
          in: header
          required: false
          description: >-
            If supplied, we can use this to identify exact requests during
            troubleshooting. Must be globally unique to be useful.
          schema:
            type: string
            example: DEEE3D21-F0FA-459E-87BB-A565DBCC0784
        - name: id
          in: path
          required: true
          description: The ID of the division to which to limit the results.
          schema:
            type: integer
            format: integer
            example: 1234
        - name: seasonid
          in: query
          required: true
          description: The ID of the season to which to limit the results.
          schema:
            type: integer
            format: integer
            example: 2023
        - name: clientid
          in: query
          required: true
          description: The ID of the client to which to limit the results.
          schema:
            type: integer
            format: integer
            example: 754
      tags:
        - Divisions
  /attendees:
    get:
      summary: List Attendees
      description: Returns division attendees that match the supplied criteria.
      operationId: ListAttendees
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  TotalCount:
                    type: integer
                    description: The total number of records returned in the call.
                  Next:
                    type: string
                    description: The link to the next page of records.
                  Results:
                    type: array
                    description: The array of records returned.
                    items:
                      $ref: '#/components/schemas/AttendeeResponse'
        '400':
          description: >-
            This request is invalid. It is either missing required parameters or
            one of the supplied parameters is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 400
                message: '''pagenumber'' is invalid'
        '401':
          description: >-
            This request lacks valid credentials, please try again making sure
            to supply a valid token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 401
                message: Unauthorized
        '403':
          description: >-
            The supplied credentials do not have permission to make this
            request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 403
                message: Forbidden
        '500':
          description: >-
            Our server could not process this request. If the issue persists,
            contact CampMinder support.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 500
                message: Internal Server Error
      parameters:
        - name: Authorization
          in: header
          description: 'The JWT token should be in the format `Bearer {token}`.'
          required: true
          schema:
            type: string
            example: >-
              Bearer
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - name: X-Request-ID
          in: header
          required: false
          description: >-
            If supplied, we can use this to identify exact requests during
            troubleshooting. Must be globally unique to be useful.
          schema:
            type: string
            example: DEEE3D21-F0FA-459E-87BB-A565DBCC0784
        - name: pagenumber
          in: query
          required: true
          description: Which page of PageSize results
          schema:
            type: integer
            minimum: 1
            maximum: 1000000000
            format: integer
            example: 1
        - name: pagesize
          in: query
          required: true
          description: How many results per page
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            format: integer
            example: 25
        - name: clientid
          in: query
          required: true
          description: The ID of the client to which to limit the results.
          schema:
            type: integer
            format: integer
            example: 754
        - name: seasonid
          in: query
          required: true
          description: The ID of the season to which to limit the results.
          schema:
            type: integer
            format: integer
            example: 2023
        - name: personids
          in: query
          required: false
          description: The ID of the person/people to which to limit the results.
          explode: true
          schema:
            type: array
            items:
              type: integer
              format: int64
            example:
              - 1234
              - 2345
        - name: divisionids
          in: query
          required: false
          description: The ID of the division(s) to which to limit the results.
          explode: true
          schema:
            type: array
            items:
              type: integer
              format: int64
            example:
              - 99
              - 100
      tags:
        - Divisions
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
  - jwtBearerAuth: []
servers:
  - url: 'https://api.campminder.com/divisions'
tags:
  - name: Divisions
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      description: >-
        Required for protected endpoints. Only one of the two apiKey security
        schemes is required.
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      description: >-
        Required for protected endpoints. Only one of the two apiKey security
        schemes is required.
      name: subscription-key
      in: query
    jwtBearerAuth:
      type: http
      description: Use the auth service to generate a valid JWT token.
      scheme: bearer
      bearerFormat: JWT
  schemas:
    AttendeeResponse:
      type: object
      properties:
        ID:
          type: integer
          example: 123
          description: The within-object canonical identifier of the API object.
        Self:
          type: string
          example: /v0/divisions/123/attendees/123
          description: The cross-object canonical identifier of the API object.
        ClientID:
          type: integer
          example: 754
          description: The ID of the client to which this API object belongs.
        SeasonID:
          type: integer
          example: 2023
          description: The ID of the season to which this API object belongs.
        PersonID:
          type: integer
          example: 1234
          description: >-
            The ID of the person that is assigned to the division with ID
            DivisionID.
        DivisionID:
          type: integer
          example: 101
          description: >-
            The ID of the division that is assigned to the person with ID
            PersonID.
    DivisionAttendeeResponse:
      type: object
      properties:
        DivisionID:
          type: integer
          example: 123123
          description: >-
            The ID of the division that is assigned to the person/people with ID
            in PersonIDs.
        SeasonID:
          type: integer
          example: 2023
          description: The ID of the season to which this API object belongs.
        ClientID:
          type: integer
          example: 754
          description: The ID of the client to which this API object belongs.
        PersonIDs:
          type: array
          items:
            type: integer
    DivisionResponse:
      type: object
      properties:
        ID:
          type: integer
          example: 123123
          description: Division ID.
        Self:
          type: string
          example: /v0/divisions/123123
          description: Self reference link for the division.
        ClientID:
          type: integer
          example: 754
          description: The ID of the client to which this API object belongs.
        Name:
          type: string
          example: Upper Juniors
          description: The name of the division.
        Description:
          type: string
          example: sweet thing
          description: The description of the division.
        StartGradeRangeID:
          type: integer
          example: 1
          description: The ID of the start of the division's grade range.
        EndGradeRangeID:
          type: integer
          example: 7
          description: The ID of the end of the division's grade range.
        AssignDuringCamperEnrollment:
          type: boolean
          description: >-
            If true, this division will be assigned during camper enrollment to
            campers that fit the grade range.
        GenderID:
          type: integer
          example: 2
          description: The ID of the gender of the division.
        Capacity:
          type: integer
          example: 100
          description: >-
            The capacity of the division. This isn't protected by the system, it
            is just for record keeping.
        SubOfDivisionID:
          type: integer
          example: 11
          description: >-
            If populated, the division is configured to be a subdvision to
            another division, and this is the ID of that division.
        StaffOnly:
          type: boolean
          description: True if the division's configured to contain only staff.
    Response:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
