openapi: 3.0.0
info:
  title: Staff API
  description: This API will give access to staff data
  version: '2024-06-17'
  contact:
    url: 'https://campminder.com'
paths:
  /positions:
    get:
      summary: List Positions
      description: Returns the staff positions.
      operationId: Positions
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  TotalCount:
                    type: integer
                    description: The total number of records returned in the call.
                  Next:
                    type: string
                    description: The link to the next page of records.
                  Results:
                    type: array
                    description: The array of records returned.
                    items:
                      $ref: '#/components/schemas/PositionsResponse'
        '400':
          description: >-
            This request is invalid. It is either missing required parameters or
            one of the supplied parameters is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 400
                message: '''pagenumber'' is invalid'
        '401':
          description: >-
            This request lacks valid credentials, please try again making sure
            to supply a valid token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 401
                message: Unauthorized
        '403':
          description: >-
            The supplied credentials do not have permission to make this
            request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 403
                message: Forbidden
        '500':
          description: >-
            Our server could not process this request. If the issue persists,
            contact CampMinder support.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 500
                message: Internal Server Error
      parameters:
        - name: Authorization
          in: header
          description: 'The JWT token should be in the format `Bearer {token}`.'
          required: true
          schema:
            type: string
            example: >-
              Bearer
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - name: X-Request-ID
          in: header
          required: false
          description: >-
            If supplied, we can use this to identify exact requests during
            troubleshooting. Must be globally unique to be useful.
          schema:
            type: string
            example: DEEE3D21-F0FA-459E-87BB-A565DBCC0784
        - name: clientid
          in: query
          required: false
          description: The Id of Client used to select the data
          schema:
            type: integer
            minimum: 1
            maximum: 1000000000
            format: integer
            example: 754
        - name: pagenumber
          in: query
          required: true
          description: The Page Number of the iterative call when querying lists
          schema:
            type: integer
            minimum: 1
            maximum: 1000000000
            format: integer
            example: 1
        - name: pagesize
          in: query
          required: true
          description: The Page Number of the iterative call when querying lists
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            format: integer
            example: 10
      tags:
        - Staff
  /organizationalcategories:
    get:
      summary: List Organizational Categories
      description: Returns the staff organizational categories.
      operationId: OrganizationalCategories
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  TotalCount:
                    type: integer
                    description: The total number of records returned in the call.
                  Next:
                    type: string
                    description: The link to the next page of records.
                  Results:
                    type: array
                    description: The array of records returned.
                    items:
                      $ref: '#/components/schemas/OrganizationalCategoriesResponse'
        '400':
          description: >-
            This request is invalid. It is either missing required parameters or
            one of the supplied parameters is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 400
                message: '''pagenumber'' is invalid'
        '401':
          description: >-
            This request lacks valid credentials, please try again making sure
            to supply a valid token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 401
                message: Unauthorized
        '403':
          description: >-
            The supplied credentials do not have permission to make this
            request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 403
                message: Forbidden
        '500':
          description: >-
            Our server could not process this request. If the issue persists,
            contact CampMinder support.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 500
                message: Internal Server Error
      parameters:
        - name: Authorization
          in: header
          description: 'The JWT token should be in the format `Bearer {token}`.'
          required: true
          schema:
            type: string
            example: >-
              Bearer
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - name: X-Request-ID
          in: header
          required: false
          description: >-
            If supplied, we can use this to identify exact requests during
            troubleshooting. Must be globally unique to be useful.
          schema:
            type: string
            example: DEEE3D21-F0FA-459E-87BB-A565DBCC0784
        - name: clientid
          in: query
          required: false
          description: The Id of Client used to select the data
          schema:
            type: integer
            minimum: 1
            maximum: 1000000000
            format: integer
            example: 754
        - name: pagenumber
          in: query
          required: true
          description: The Page Number of the iterative call when querying lists
          schema:
            type: integer
            minimum: 1
            maximum: 1000000000
            format: integer
            example: 1
        - name: pagesize
          in: query
          required: true
          description: The Page Number of the iterative call when querying lists
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            format: integer
            example: 10
      tags:
        - Staff
  /programareas:
    get:
      summary: List Program Areas
      description: Returns the staff program areas.
      operationId: ProgramAreas
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  TotalCount:
                    type: integer
                    description: The total number of records returned in the call.
                  Next:
                    type: string
                    description: The link to the next page of records.
                  Results:
                    type: array
                    description: The array of records returned.
                    items:
                      $ref: '#/components/schemas/ProgramAreasResponse'
        '400':
          description: >-
            This request is invalid. It is either missing required parameters or
            one of the supplied parameters is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 400
                message: '''pagenumber'' is invalid'
        '401':
          description: >-
            This request lacks valid credentials, please try again making sure
            to supply a valid token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 401
                message: Unauthorized
        '403':
          description: >-
            The supplied credentials do not have permission to make this
            request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 403
                message: Forbidden
        '500':
          description: >-
            Our server could not process this request. If the issue persists,
            contact CampMinder support.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 500
                message: Internal Server Error
      parameters:
        - name: Authorization
          in: header
          description: 'The JWT token should be in the format `Bearer {token}`.'
          required: true
          schema:
            type: string
            example: >-
              Bearer
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - name: X-Request-ID
          in: header
          required: false
          description: >-
            If supplied, we can use this to identify exact requests during
            troubleshooting. Must be globally unique to be useful.
          schema:
            type: string
            example: DEEE3D21-F0FA-459E-87BB-A565DBCC0784
        - name: clientid
          in: query
          required: false
          description: The Id of Client used to select the data
          schema:
            type: integer
            minimum: 1
            maximum: 1000000000
            format: integer
            example: 754
        - name: pagenumber
          in: query
          required: true
          description: The Page Number of the iterative call when querying lists
          schema:
            type: integer
            minimum: 1
            maximum: 1000000000
            format: integer
            example: 1
        - name: pagesize
          in: query
          required: true
          description: The Page Number of the iterative call when querying lists
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            format: integer
            example: 10
      tags:
        - Staff
  /:
    get:
      summary: List Staff
      description: Returns a list of Staff that match the supplied criteria.
      operationId: ListStaff
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  TotalCount:
                    type: integer
                    description: The total number of records returned in the call.
                  Next:
                    type: string
                    description: The link to the next page of records.
                  Results:
                    type: array
                    description: The array of records returned.
                    items:
                      $ref: '#/components/schemas/ListStaffResponse'
        '400':
          description: >-
            This request is invalid. It is either missing required parameters or
            one of the supplied parameters is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 400
                message: '''pagenumber'' is invalid'
        '401':
          description: >-
            This request lacks valid credentials, please try again making sure
            to supply a valid token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 401
                message: Unauthorized
        '403':
          description: >-
            The supplied credentials do not have permission to make this
            request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 403
                message: Forbidden
        '500':
          description: >-
            Our server could not process this request. If the issue persists,
            contact CampMinder support.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 500
                message: Internal Server Error
      parameters:
        - name: Authorization
          in: header
          description: 'The JWT token should be in the format `Bearer {token}`.'
          required: true
          schema:
            type: string
            example: >-
              Bearer
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - name: X-Request-ID
          in: header
          required: false
          description: >-
            If supplied, we can use this to identify exact requests during
            troubleshooting. Must be globally unique to be useful.
          schema:
            type: string
            example: DEEE3D21-F0FA-459E-87BB-A565DBCC0784
        - name: clientid
          in: query
          required: false
          description: The Id of Client used to select the data
          schema:
            type: integer
            minimum: 1
            maximum: 1000000000
            format: integer
            example: 754
        - name: organizationalcategories
          in: query
          required: false
          description: Filter by Organization Category Ids
          explode: true
          schema:
            type: array
            items:
              type: integer
              minimum: 1
              maximum: 1000000000
              format: int64
            example:
              - 123456
              - 123457
        - name: positions
          in: query
          required: false
          description: Filter by Organization Position Ids
          explode: true
          schema:
            type: array
            items:
              type: integer
              minimum: 1
              maximum: 1000000000
              format: int64
            example:
              - 223456
              - 223457
        - name: programareas
          in: query
          required: false
          description: Filter by Organization Program Area Ids
          explode: true
          schema:
            type: array
            items:
              type: integer
              minimum: 1
              maximum: 1000000000
              format: int64
            example:
              - 285663
              - 286668
        - name: seasonid
          in: query
          required: true
          description: Filter by Season Id. This is required
          schema:
            type: integer
            minimum: 1900
            maximum: 4000
            format: integer
            example: 2022
        - name: status
          in: query
          required: true
          description: 'Filter by Status Id. 1-Active, 2-Resigned, 3-Dismissed, 4-Cancelled'
          schema:
            type: integer
            minimum: 1
            maximum: 1000000000
            format: integer
            example: 1
        - name: pagenumber
          in: query
          required: true
          description: The Page Number of the iterative call when querying lists
          schema:
            type: integer
            minimum: 1
            maximum: 1000000000
            format: integer
            example: 1
        - name: pagesize
          in: query
          required: true
          description: The Page Number of the iterative call when querying lists
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            format: integer
            example: 10
        - name: lastupdated
          in: query
          required: false
          description: >-
            A datetime, formatted as an RFC3339 string, representing the cutoff
            before which you are not interested in the results.
          schema:
            type: string
            minimum: 0
            maximum: 0
            format: string
            example: '2023-02-20T23:20:50.52Z'
        - name: divisionids
          in: query
          required: false
          description: Filter by Divison Ids
          explode: true
          schema:
            type: array
            items:
              type: integer
              minimum: 1
              maximum: 1000000000
              format: int64
            example:
              - 887542
              - 887543
        - name: personids
          in: query
          required: false
          description: Filter by person IDs
          explode: true
          schema:
            type: array
            items:
              type: integer
              minimum: 1
              maximum: 1000000000
              format: int64
            example:
              - 887542
              - 887543
      tags:
        - Staff
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
  - jwtBearerAuth: []
servers:
  - url: 'https://api.campminder.com/staff'
tags:
  - name: Staff
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      description: >-
        Required for protected endpoints. Only one of the two apiKey security
        schemes is required.
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      description: >-
        Required for protected endpoints. Only one of the two apiKey security
        schemes is required.
      name: subscription-key
      in: query
    jwtBearerAuth:
      type: http
      description: Use the auth service to generate a valid JWT token.
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BunkAssignment:
      type: object
      properties:
        ID:
          type: integer
          example: 66585
          description: The Bunk Id
    ListStaffResponse:
      type: object
      properties:
        PersonID:
          type: integer
          example: 123456
          description: ''
        ClientID:
          type: integer
          example: 754
          description: ''
        SeasonID:
          type: integer
          example: 2022
          description: ''
        StatusID:
          type: integer
          example: 1
          description: 'The Staff Status. 1-Active, 2-Resigned, 3-Dismissed, 4-Cancelled'
        StatusName:
          type: string
          example: Active
          description: 'Active, Resigned, Dismissed or Cancelled'
        OrganizationalCategoryID:
          type: integer
          example: 123456
          description: ''
        Position1ID:
          type: integer
          example: 253645
          description: Staff can be assigned to two Positions. This is the first.
        Position2ID:
          type: integer
          example: 253646
          description: Staff can be assigned to two Positions. This is the second.
        BunkAssignments:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/BunkAssignment'
        DivisionID:
          type: integer
          example: 187546
          description: The assigned DivisionId
        HireDate:
          type: string
          example: '2023-05-13'
          description: The Hire Date in ISO 8601 format (YYYY-MM-DD)
        EmploymentStartDate:
          type: string
          example: '2023-05-13'
          description: The Date Employment begins in ISO 8601 format (YYYY-MM-DD)
        EmploymentEndDate:
          type: string
          example: '2023-05-13'
          description: The Date Employment ends in ISO 8601 format (YYYY-MM-DD)
        ContractInDate:
          type: string
          example: '2023-05-13'
          description: The Date the Contrect was received in ISO 8601 format (YYYY-MM-DD)
        ContractOutDate:
          type: string
          example: '2023-05-13'
          description: The Date the Contract was sent in ISO 8601 format (YYYY-MM-DD)
        ContractDueDate:
          type: string
          example: '2023-05-13'
          description: The Date the Contract is due in ISO 8601 format (YYYY-MM-DD)
        International:
          type: string
          example: Domestic
          description: International or Domestic
        Years:
          type: integer
          example: 2
          description: Years as staff
        Salary:
          type: number
          example: 1800
          description: The salary paid
        BunkStaff:
          type: boolean
          example: true
          description: >-
            Whether or not this person is Bunk Staff. Value will be null if it
            hasn't been set.
        LastUpdatedUTC:
          type: string
          example: '2023-02-22T02:58:44.9800Z'
          description: >-
            The UTC datetime as an RFC3339 string of when this person was last
            updated or modified.
    OrganizationalCategoriesResponse:
      type: object
      properties:
        ID:
          type: integer
          example: 12345
          description: ''
        Name:
          type: string
          example: position
          description: ''
    PositionsResponse:
      type: object
      properties:
        ID:
          type: integer
          example: 12345
          description: ''
        Name:
          type: string
          example: position
          description: ''
        ProgramAreaID:
          type: integer
          example: 485
          description: The Program Area Id assigned to this Position
        ProgramAreaName:
          type: string
          example: Sample Program
          description: The Program Area Name assigned to this Position
    ProgramAreasResponse:
      type: object
      properties:
        ID:
          type: integer
          example: 12345
          description: ''
        Name:
          type: string
          example: position
          description: ''
    Response:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
